// <auto-generated>
//   This file provides the Windows entry point that would normally be generated
//   by the WinUI XAML compiler from App.xaml. Created manually for Linux cross-compilation.
// </auto-generated>
using System;

namespace AstroTool.WinUI;

partial class App
{
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    private void InitializeComponent()
    {
        // No XAML resources to initialize (no App.xaml)
    }

    [global::System.STAThread]
    static void Main(string[] args)
    {
        global::WinRT.ComWrappersSupport.InitializeComWrappers();
        global::Microsoft.UI.Xaml.Application.Start((p) =>
        {
            var context = new global::Microsoft.UI.Dispatching.DispatcherQueueSynchronizationContext(
                global::Microsoft.UI.Dispatching.DispatcherQueue.GetForCurrentThread());
            global::System.Threading.SynchronizationContext.SetSynchronizationContext(context);
            new App();
        });
    }
}
