name: Setup DotNet Common

description: Configure .NET SDK with NuGet cache for faster builds

inputs:
  dotnet-version:
    description: Dotnet SDK version
    required: false
    default: "10.0.x"

runs:
  using: composite
  steps:
    - name: Set up .NET
      uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
        cache: true
        cache-dependency-path: |
          **/*.csproj
          global.json
          Directory.Packages.props
          **/packages.lock.json
